openapi: 3.0.3
info:
  title: Coffee Shop - OpenAPI 3.0
  description: |-
    This is the best coffee shop in the world, as featured on the hit movie, ELF.
    
    - [coffee shop repository](https://github.com/swagger-api/swagger-petstore)
  contact:
    email: joshua.haddad@ge.com
  version: 1.0.11
servers:
  - url: https://github.com/Bryson14/MicroservicesACourse
paths:
  /orders:
    get:
      summary: Returns a list of all orders
      description: Gets all the orders that are currently open
      responses:
        '200':
          description: A JSON array of order objects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  schema:
                  $ref: '#/components/schemas/Order'
  /order:
    post:
      summary: Add a new order
      description: Place a new unique order onto the queue
      responses:
        '200':
          description: The order object of the newly created order
          content:
            application/json:
              schema:
                type: object
                schema:
                $ref: '#/components/schemas/Order'
        '401':
          description: Bad request message
          content:
            application/json:
              schema:
                type: string
                example: Bad request due to duplicate information or whatever
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        orderItems:
          type: array
          items:
            type: object
            schema: 
            $ref: '#/components/schemas/Item'
        createdTimestamp:
          type: string
          format: date-time
        status:
          type: string
          description: Order Status
          example: approved
          enum:
            - placed
            - delivered
        customerName:
          type: string
          description: The name of the customer ordering
          example: Huzaifah Shamim
      xml:
        name: order
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        Name:
          type: string
          example: "Best Latte Ever"
        Price:
          type: number
          format: float
      xml:
        name: order
