# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.item import Item
from openapi_server import util

from openapi_server.models.item import Item  # noqa: E501

class NewOrder(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, order_items=None, status=None, customer_name=None, discount=None):  # noqa: E501
        """NewOrder - a model defined in OpenAPI

        :param order_items: The order_items of this NewOrder.  # noqa: E501
        :type order_items: List[Item]
        :param status: The status of this NewOrder.  # noqa: E501
        :type status: str
        :param customer_name: The customer_name of this NewOrder.  # noqa: E501
        :type customer_name: str
        :param discount: The discount of this NewOrder.  # noqa: E501
        :type discount: float
        """
        self.openapi_types = {
            'order_items': List[Item],
            'status': str,
            'customer_name': str,
            'discount': float
        }

        self.attribute_map = {
            'order_items': 'orderItems',
            'status': 'status',
            'customer_name': 'customerName',
            'discount': 'discount'
        }

        self._order_items = order_items
        self._status = status
        self._customer_name = customer_name
        self._discount = discount

    @classmethod
    def from_dict(cls, dikt) -> 'NewOrder':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NewOrder of this NewOrder.  # noqa: E501
        :rtype: NewOrder
        """
        return util.deserialize_model(dikt, cls)

    @property
    def order_items(self):
        """Gets the order_items of this NewOrder.


        :return: The order_items of this NewOrder.
        :rtype: List[Item]
        """
        return self._order_items

    @order_items.setter
    def order_items(self, order_items):
        """Sets the order_items of this NewOrder.


        :param order_items: The order_items of this NewOrder.
        :type order_items: List[Item]
        """

        self._order_items = order_items

    @property
    def status(self):
        """Gets the status of this NewOrder.

        Order Status  # noqa: E501

        :return: The status of this NewOrder.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this NewOrder.

        Order Status  # noqa: E501

        :param status: The status of this NewOrder.
        :type status: str
        """
        allowed_values = ["placed", "delivered"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def customer_name(self):
        """Gets the customer_name of this NewOrder.

        The name of the customer ordering  # noqa: E501

        :return: The customer_name of this NewOrder.
        :rtype: str
        """
        return self._customer_name

    @customer_name.setter
    def customer_name(self, customer_name):
        """Sets the customer_name of this NewOrder.

        The name of the customer ordering  # noqa: E501

        :param customer_name: The customer_name of this NewOrder.
        :type customer_name: str
        """

        self._customer_name = customer_name

    @property
    def discount(self):
        """Gets the discount of this NewOrder.


        :return: The discount of this NewOrder.
        :rtype: float
        """
        return self._discount

    @discount.setter
    def discount(self, discount):
        """Sets the discount of this NewOrder.


        :param discount: The discount of this NewOrder.
        :type discount: float
        """

        self._discount = discount
