openapi: 3.0.3
info:
  title: Coffee Shop - OpenAPI 3.0
  description: |-
    This is the best coffee shop in the world, as featured on the hit movie, ELF.

    - [coffee shop repository](https://github.com/Bryson14/MicroservicesACourse)
  contact:
    email: joshua.haddad@ge.com
    url: https://github.com/Bryson14/MicroservicesACourse
  version: 1.0.11
paths:
  /orders:
    get:
      summary: Returns a list of all orders
      description: Gets all the orders that are currently open
      parameters:
        - in: query
          name: customername
          schema:
            type: string
          description: The name of the customer to filter the result by
      responses:
        "200":
          description: A JSON array of order objects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  schema:
                  $ref: "#/components/schemas/Order"
  /order:
    post:
      summary: Add a new order
      description: Place a new unique order onto the queue
      requestBody:
        description: A new order object without time/uid fields of an order
        required: true
        content:
          application/json:
            schema:
              type: object
              schema:
              $ref: "#/components/schemas/NewOrder"
          
      responses:
        "200":
          description: The order object of the newly created order
          content:
            application/json:
              schema:
                type: object
                schema:
                $ref: "#/components/schemas/Order"
        "401":
          description: Bad request message
          content:
            application/json:
              schema:
                type: string
                example: Bad request due to duplicate information or whatever
  /order/{uid}:
    get:
      summary: Returns a given order uid as json
      parameters:
        - in: path
          name: uid
          description: The uid associated with an order
          required: true
          schema:
            type: integer
          example: 10
      responses:
        "200":
          description: A JSON representation of a single order given by the uid
          content:
            application/json:
              schema:
                type: object
                schema:
                $ref: "#/components/schemas/Order"
        "406":
          description: Order uid not found
          content:
            application/json:
              schema:
                type: string
                example: Order uid not found
    delete:
      summary: Cancels an order
      description: Canceles an order
      operationId: deleteOrder
      parameters:
        - name: uid
          in: path
          description: Order uid to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "406":
          description: Invaluid order uid, please try again.
          content:
            application/json:
              schema:
                type: string
                example: Bad request
        "200":
          description: Order cancelled successfully.
  /order/{uid}/{status}:
    patch:
      summary: Update an existing order
      description: Update an existing order
      operationId: patchOrder
      parameters:
        - name: uid
          in: path
          description: uid associated with order
          required: true
          schema:
            type: integer
            format: int64
            example: 10
        - name: status
          in: path
          description: Change order status
          required: true
          schema:
            type: string
            example: "delivered"
      requestBody:
        description: Json of item to add
        content:
          application/json:
            schema:
              type: object
              schema:
              $ref: "#/components/schemas/Item"
      responses:
        "200":
          description: Order updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
            application/xml:
              schema:
                $ref: "#/components/schemas/Order"
        "400":
          description: Invaluid uid supplied
        "401":
          description: Invalid format
        "404":
          description: Order not found
        "406":
          description: Validation exception
components:
  schemas:
    Order:
      type: object
      properties:
        uid:
          type: integer
          format: int64
          example: 10
        orderItems:
          type: array
          items:
            type: object
            schema:
            $ref: "#/components/schemas/Item"
        createdTimestamp:
          type: string
          format: date-time
        status:
          type: string
          description: Order Status
          example: placed
          enum:
            - placed
            - delivered
        customername:
          type: string
          description: The name of the customer ordering
          example: Huzaifah Shamim
        discount:
          type: number
          format: float
          example: 2.00
      xml:
        name: order
    Item:
      type: object
      properties:
        uid:
          type: integer
          format: int64
          example: 10.99
        name:
          type: string
          example: "Best Latte Ever"
        price:
          type: number
          format: float
      xml:
        name: item
    NewOrder:
      type: object
      properties:
        orderItems:
          type: array
          items:
            type: object
            schema:
            $ref: "#/components/schemas/Item"
        status:
          type: string
          description: Order Status
          example: placed
          enum:
            - placed
            - delivered
        customername:
          type: string
          description: The name of the customer ordering
          example: Huzaifah Shamim
        discount:
          type: number
          format: float
          example: 2.00
      xml:
        name: new_order
    Customer:
      type: object
      properties:
        uid:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: "Bryson Meiling"
        birthday:
          type: string
          format: date
          example: 12-26
        rewardPoints:
          type: integer
          format: int32
          example: 5030

      xml:
        name: customer
